---
name: style

on:
  pull_request:
  push:

jobs:
  style:
    name: style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dependencies
        run: |
          sudo apt update
          sudo apt install doxygen astyle python3
      - name: check
        run: |
          python3 astyle.py
          UBX_WORKDIR="$(pwd)" doxygen
